apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - infrastructure.yaml
  - order-service.yaml
  - inventory-consumer.yaml
  - payment-consumer.yaml
  - warehouse-consumer.yaml
  - delivery-consumer.yaml
  - saga-monitor.yaml
  - other-services.yaml

namespace: fulfilbox

images:
  - name: fulfilbox/inventory-consumer
    newTag: latest
  - name: fulfilbox/payment-consumer
    newTag: latest
  - name: fulfilbox/warehouse-consumer
    newTag: latest
  - name: fulfilbox/delivery-consumer
    newTag: latest
  - name: fulfilbox/saga-monitor
    newTag: latest
  - name: fulfilbox/student-portal
    newTag: latest
