apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-consumer
  namespace: fulfilbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fulfilbox-warehouse-consumer
  template:
    metadata:
      labels:
        app: fulfilbox-warehouse-consumer
    spec:
      containers:
        - name: warehouse-consumer
          image: fulfilbox/warehouse-consumer:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8012
          env:
            - name: DATABASE_URL
              value: "postgresql://fulfilbox:fulfilbox@fulfilbox-postgres:5432/fulfilbox"
            - name: REDIS_URL
              value: "redis://fulfilbox-redis:6379/0"
            - name: KAFKA_BROKER_URL
              value: "fulfilbox-kafka:9092"
            - name: METRICS_PORT
              value: "8012"
            - name: SAGA_STEP_DELAY_MIN
              value: "1"
            - name: SAGA_STEP_DELAY_MAX
              value: "3"
