apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fulfilbox.fullname" . }}-config
  labels:
    {{- include "fulfilbox.labels" . | nindent 4 }}
data:
  DATABASE_URL: {{ include "fulfilbox.databaseUrl" . | quote }}
  REDIS_URL: {{ include "fulfilbox.redisUrl" . | quote }}
  KAFKA_BROKER_URL: {{ include "fulfilbox.kafkaBrokerUrl" . | quote }}
