{{- if .Values.orderService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-order-service
  labels:
    app: {{ .Release.Name }}-order-service
    {{- include "fulfilbox.labels" . | nindent 4 }}
spec:
  {{- if not .Values.orderService.hpa.enabled }}
  replicas: {{ .Values.orderService.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-order-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-order-service
    spec:
      containers:
        - name: order-service
          image: {{ .Values.orderService.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.orderService.port }}
              name: http
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "fulfilbox.fullname" . }}-config
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "fulfilbox.fullname" . }}-config
                  key: REDIS_URL
            - name: KAFKA_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "fulfilbox.fullname" . }}-config
                  key: KAFKA_BROKER_URL
          resources:
            {{- toYaml .Values.orderService.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.orderService.port }}
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.orderService.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-order-service
  labels:
    app: {{ .Release.Name }}-order-service
spec:
  ports:
    - port: {{ .Values.orderService.port }}
      targetPort: {{ .Values.orderService.port }}
  selector:
    app: {{ .Release.Name }}-order-service
{{- end }}
